name: List Artifacts

on:
  workflow_dispatch:

jobs:
  build:
#    runs-on: macos-11
    runs-on: ubuntu-latest

    steps:
      - name: S3 Sync
##        uses: ItsKarma/aws-cli@v1.70.0
##        with:
##          args: s3 ls s3://artifacts.fiiish-rs.omnimad.net/
        run: |
          aws s3 ls s3://artifacts.fiiish-rs.omnimad.net/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"        
