name: Pack Fiiish Data

on:
  # :TODO: add push
  workflow_dispatch:
    inputs:
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: choice
        options:
          - latest
          - auto
          - ref
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string
        
jobs:
  build:
#    runs-on: ubuntu-linux
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 1
#          lfs: ''
#          submodules: ''

      # :TODO: setup platform specific dependencies

      - name: Generate VERSION
        run: |
          VERSION=${{ github.sha }}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          # DATE=$(git show -s --format=%ci ${{ github.sha }}|cut -b1-10)
          DATE=$(git show -s --format=%ci HEAD|cut -b1-10)
          echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Prepare Variables
        run: |
          if [ "${{ runner.os }}" = "macos-11" ]
          then
            temp=$(mktemp -d temp)
          else
            temp=$(mktemp)
          fi
          echo "TEMP=${temp}" >> $GITHUB_ENV
          echo "TEMP=${temp}"
          archive=fiiish-rs-fiiish-data-${{ env.VERSION }}.tgz
          archive_folder=${{ env.DATE }}/${{ env.VERSION }}
          echo "ARCHIVE=${archive}" >> $GITHUB_ENV
          echo "ARCHIVE_FOLDER=${archive_folder}" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache crates
        uses: actions/cache@v2
        env:
          cache-name: cache-crates
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('fiiish-rs/Cargo.lock') }}

          # :TODO: technically the above key is wrong

      - name: Install omt
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: omt

      - name: Pack fiiish data
        run: |
          ./workflow/helpers/pack_data.sh fiiish-data fiiish-data.omar paklist.txt music_mp3

      - name: Add build number
        run: |
          echo "Adding build number"
          cp build_number.txt ${{ env.TEMP }}/

      - name: Add data
        run: |
          echo "Adding data"
          cp fiiish-data.omar ${{ env.TEMP }}/

      - name: List result
        run: |
          echo "sha:        ${{ github.sha }}"
          echo "ref_name:   ${{ github.ref_name }}"
          echo "ref:        ${{ github.ref }}"
          echo "ref_type:   ${{ github.ref_type }}"
          echo "event_name: ${{ github.event_name }}"
          echo "actor:      ${{ github.actor }}"
          ls -l ${{ env.TEMP }}/
          
      - name: Create archive
        run: |
          cd ${{ env.TEMP }}
          tar czf ${{ env.ARCHIVE }} .
          
      - name: Sync archive to S3
        run: |
          aws s3 sync ${{ env.ARCHIVE }} s3://artifacts.fiiish-rs.omnimad.net/${{ env.ARCHIVE_FOLDER }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"        

###   - name: Upload Articacts for fiiish-data
###     uses: actions/upload-artifact@v3
###     with:
###       name: fiiish-data-${{ env.VERSION }}-music_mp3
###       path: |
###         fiiish-data.omar
###         build_number.txt
          
