name: Release version

on:
  workflow_dispatch:
    inputs:
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: choice
        options:
          - latest
          - auto
          - ref
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string
  workflow_call:
    inputs:
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: string
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string
    secrets:
      ITCHIO_API_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare
        run: |
          echo "Prepare"

      # :TODO: add build, pack, package, etc
#      - name: Push to itch.io
# internal      
#        uses: ./.github/workflows/push_to_itchio.yaml
# external - job level !

  build_runtime:
    uses:  AndreasOM/fiiish-rs/.github/workflows/build_runtime.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  pack_fiiish_data:
    uses:  AndreasOM/fiiish-rs/.github/workflows/pack_fiiish_data.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  pack_dummy_data:
    uses:  AndreasOM/fiiish-rs/.github/workflows/pack_dummy_data.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  create_packages:
    needs: [build_runtime,pack_fiiish_data,pack_dummy_data]
    uses:  AndreasOM/fiiish-rs/.github/workflows/create_packages.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  push_to_itchio:
    needs: create_packages
    uses:  AndreasOM/fiiish-rs/.github/workflows/push_to_itchio.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}


