name: Release version

on:
  push:
    tags:
      - "*-test"  
  workflow_dispatch:
    inputs:
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: choice
        options:
          - latest
          - auto
          - ref
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare
        run: |
          echo "Prepare"

  pack_fiiish_data:
    uses:  AndreasOM/fiiish-rs/.github/workflows/pack_fiiish_data.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  pack_dummy_data:
    uses:  AndreasOM/fiiish-rs/.github/workflows/pack_dummy_data.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build_package_and_sign_macos:
    needs:
      - pack_dummy_data
      - pack_fiiish_data
    uses:  AndreasOM/fiiish-rs/.github/workflows/build_package_and_sign_macos.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref || github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CODESIGN_CERT: ${{ secrets.CODESIGN_CERT }}
      CODESIGN_CERT_PASS: ${{ secrets.CODESIGN_CERT_PASS }}
      CODESIGN_CERT_IDENTITY: ${{ secrets.CODESIGN_CERT_IDENTITY }}

  push_to_itchio:
    needs: build_package_and_sign_macos
    uses:  AndreasOM/fiiish-rs/.github/workflows/push_to_itchio.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}


