name: Release version

on:
  workflow_dispatch:
    inputs:
      # maybe we don't need this
      version:
        description: 'Version'
        required: true
        default: 'auto'
        type: choice
        options:
          - latest
          - auto
          - ref
      ref:
        description: 'The branch, tag, or SHA of the commit to build'
        required: false
        default: ''
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Prepare
        run: |
          echo "Prepare"

      # :TODO: add build, pack, package, etc
#      - name: Push to itch.io
# internal      
#        uses: ./.github/workflows/push_to_itchio.yaml
# external - job level !

  push_to_itchio:
    uses:  AndreasOM/fiiish-rs/.github/workflows/creates_packages.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  push_to_itchio:
    uses:  AndreasOM/fiiish-rs/.github/workflows/push_to_itchio.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ITCHIO_API_KEY: ${{ secrets.ITCHIO_API_KEY }}


